#+title: packer-manjaro
#+author: conao3

[[https://github.com/conao3/packer-manjaro][https://raw.githubusercontent.com/conao3/files/master/blob/headers/png/packer-manjaro.png]]

[[https://github.com/conao3/packer-manjaro/blob/master/LICENSE][https://img.shields.io/github/license/conao3/packer-manjaro.svg?style=flat-square]]
[[https://github.com/conao3/packer-manjaro/releases][https://img.shields.io/github/tag/conao3/packer-manjaro.svg?style=flat-square]]

* Overview

Packer templates for building [[https://archlinux.org/][Arch Linux]] and [[https://manjaro.org/][Manjaro Linux]] Vagrant base boxes.

This project is forked from [[https://github.com/elasticdog/packer-arch][packer-arch]] and extends it with Manjaro Linux support.

* Features

- 64-bit system configuration
- 20 GB disk allocation
- 512 MB memory
- Single root partition (ext4) without swap
- Includes =base= meta package and =base-devel= group
- OpenSSH installed and enabled on boot
- Support for VirtualBox, VMware, Parallels, and libvirt providers

* Requirements

- [[https://www.packer.io/][Packer]]
- [[https://www.vagrantup.com/][Vagrant]]
- One of the following providers:
  - [[https://www.virtualbox.org/][VirtualBox]]
  - [[https://www.vmware.com/products/fusion/][VMware Fusion]] / [[https://www.vmware.com/products/workstation/][Workstation]]
  - [[http://www.parallels.com/][Parallels]]
  - [[https://github.com/vagrant-libvirt/vagrant-libvirt][libvirt]]

** Quick Install (Arch/Manjaro)

#+begin_src sh
yay -S linux-headers virtualbox-host-dkms virtualbox vagrant packer
#+end_src

* Usage

** Building a Box

#+begin_src sh
# Clone the repository
git clone https://github.com/conao3/packer-manjaro.git
cd packer-manjaro

# Build for VirtualBox
packer build -only=virtualbox-iso manjaro-template.json

# Build for other providers
packer build -only=vmware-iso manjaro-template.json
packer build -only=parallels-iso manjaro-template.json
packer build -only=qemu manjaro-template.json
#+end_src

** Importing into Vagrant

#+begin_src sh
VERSION=20210201
vagrant box add manjaro-$VERSION output/packer_arch_virtualbox.box
#+end_src

** Starting the VM

#+begin_src sh
vagrant up
vagrant ssh
#+end_src

** SSH Configuration

#+begin_src sh
vagrant ssh-config >> ~/.ssh/config
ssh default
#+end_src

* Wrapper Script

The =wrapacker= script automates the build process with additional options:

#+begin_src sh
# Basic usage with country mirror
wrapacker --country US

# Debug mode
PACKER_LOG=1 ./wrapacker --country=US --provider=virtualbox --on-error=ask --force
#+end_src

Run =wrapacker --help= for all available options.

* Known Issues

** VMware Tools

VMware Tools do not officially support Arch Linux. The [[https://github.com/vmware/open-vm-tools][Open Virtual Machine Tools]] require patching for newer kernels. Shared folders will not work with VMware-based boxes.

VirtualBox guest additions work without issues.

** Provisioners

This box does not include Puppet, Chef, or Ansible. It provides a minimal base for testing configuration management tools like Ansible.

* License

ISC License

Copyright 2013-2017 [[mailto:aaron@elasticdog.com][Aaron Bull Schaefer]] (original packer-arch)

Copyright 2021 Naoya Yamashita
